## 异常
```python
try:
	pass
except ValueError as message:
	print('先处理个别错误，现在捕获的是ValueError')
    print(message)	# 打印异常的错误信息
except Exception:
	print('捕获所有上面的except捕获不了的ERROR')
else:
	print('try中的代码没有异常处理则执行这里')
finally:
	print('不管有没有异常都要执行的代码')
```
- 应用：with语句自动关闭文件
```python
try:
    f = open('abc', 'w')
    # f.write('123')
finally:
    f.close()
```